# command line interface (CLI) tools
brew "git"
brew "python3"
brew "ipython"

# graphical user interface (GUI) tools
cask "visual-studio-code"

# vscode extensions
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-vscode.vscode-serial-monitor"
